# Generated by Django 2.1rc1 on 2018-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_name', models.CharField(max_length=250)),
                ('page_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
